import Link from "next/link";
import { AdminHeader, Notice, Pagination, StatusBadge } from "@/components/admin/ui";
import { requireAdmin } from "@/lib/admin/auth";
import { adminRpc, integer, single } from "@/lib/admin/data";
import type { AdminQuestionResult } from "@/types/admin";
import { saveQuestionAction, setQuestionStatusAction } from "../actions";

export default async function AdminContent({ searchParams }: { searchParams:Promise<Record<string,string|string[]|undefined>> }) {
  const access=await requireAdmin("questions.view");const q=await searchParams;const search=single(q.search);const category=single(q.category);const edit=single(q.edit);const page=Math.max(1,integer(q.page,1));const canManage=access.capabilities.includes("questions.manage");
  const result=await adminRpc<AdminQuestionResult>("admin_question_analytics",{p_search:edit||search,p_category:category,p_sort:"missed",p_page:page,p_page_size:50}); const editing=edit?result.data.find(row=>row.id===edit):undefined;
  return <><AdminHeader title="Content management" description="Create, edit, review, publish, and retire QuizForge question content." /><Notice error={single(q.error)} message={single(q.message)} />
    {canManage&&<section className="admin-panel"><div className="admin-section-heading"><h2>{editing?`Edit ${editing.id}`:"Create question"}</h2>{editing&&<Link href="/admin/content">Cancel edit</Link>}</div><form className="admin-question-form" action={saveQuestionAction}><label>Question ID<input name="id" required pattern="[A-Za-z]+-[0-9]{4}" defaultValue={editing?.id}/></label><label>Category<input name="category" required defaultValue={editing?.category||"History"}/></label><label>Subcategory<input name="subcategory" required defaultValue={editing?.subcategory}/></label><label>Difficulty<select name="difficulty" defaultValue={editing?.difficulty||"medium"}><option>easy</option><option>medium</option><option>hard</option></select></label><label>Question type<select name="type" defaultValue={editing?.type||"short_answer"}><option value="short_answer">Short answer</option><option value="multiple_choice">Multiple choice</option><option value="true_false">True / false</option><option value="fill_in_the_blank">Fill in blank</option></select></label><label>Status<select name="status" defaultValue={editing?.status||"draft"}><option>draft</option><option>published</option><option>unpublished</option><option>in_review</option><option>archived</option></select></label><label className="wide">Question<textarea name="question" required minLength={10} defaultValue={editing?.question}/></label><label className="wide">Accepted answer<input name="answer" required defaultValue={editing?.acceptedAnswer}/></label><label className="wide">Explanation<textarea name="explanation" defaultValue={editing?.explanation}/></label><button className="admin-button primary">{editing?"Save question changes":"Create question"}</button></form></section>}
    <form className="admin-toolbar"><label className="admin-search">Search<input name="search" defaultValue={search} /></label><label>Category<input name="category" defaultValue={category}/></label><button className="admin-button primary">Apply</button></form><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>ID</th><th>Question</th><th>Classification</th><th>Status</th><th>Answers</th><th>Accuracy</th><th>Actions</th></tr></thead><tbody>{result.data.map(row=><tr key={row.id}><td>{row.id}</td><td><span className="admin-clamp">{row.question}</span></td><td>{row.category}<small>{row.subcategory} · {row.difficulty}</small></td><td><StatusBadge value={row.status}/></td><td>{row.attempts}</td><td>{row.accuracy}%</td><td><div className="admin-row-actions">{canManage&&<><Link className="admin-link" href={`/admin/content?edit=${row.id}`}>Edit</Link><form action={setQuestionStatusAction}><input type="hidden" name="questionId" value={row.id}/><input type="hidden" name="status" value={row.published?"unpublished":"published"}/><button>{row.published?"Unpublish":"Publish"}</button></form></>}</div></td></tr>)}</tbody></table></div><Pagination base="/admin/content" page={page} totalPages={result.pagination.totalPages} params={{search,category}} /></>;
}
