import { notFound } from "next/navigation";
import Link from "next/link";
import { Award, ArrowLeft, Flame, Target, Trophy, Zap } from "lucide-react";
import { createClient } from "@/utils/supabase/server";

type PublicProfile={username:string;displayName:string;joinedAt:string;totalXp:number;currentStreak:number;quizzesCompleted:number;correctAnswers:number;accuracy:number|null;badges:Array<{name:string;description:string;earnedAt:string}>;strongestCategories:Array<{category:string;accuracy:number}>};
export default async function PublicProfilePage({params}:{params:Promise<{username:string}>}){
  const {username}=await params;const supabase=await createClient();const {data,error}=await supabase.rpc("get_public_profile",{p_username:username});
  if(error||!data)notFound();const profile=data as PublicProfile;
  return <main className="public-profile"><Link href="/" className="public-profile-back"><ArrowLeft/> Back to QuizForge</Link><header><div className="profile-avatar">{profile.displayName.split(/\s+/).map(v=>v[0]).join('').slice(0,2).toUpperCase()}</div><div><span>QuizForge scholar</span><h1>{profile.displayName}</h1><p>@{profile.username} · Joined {new Date(profile.joinedAt).toLocaleDateString(undefined,{month:'long',year:'numeric'})}</p></div></header><section className="metric-ledger"><div className="stat"><span className="stat-label">Lifetime XP</span><strong>{profile.totalXp.toLocaleString()}</strong><small><Zap/>Trusted total</small></div><div className="stat"><span className="stat-label">Current streak</span><strong>{profile.currentStreak} days</strong><small><Flame/>Daily practice</small></div><div className="stat"><span className="stat-label">Accuracy</span><strong>{profile.accuracy==null?'—':`${profile.accuracy}%`}</strong><small><Target/>{profile.correctAnswers} correct</small></div><div className="stat"><span className="stat-label">Completed sets</span><strong>{profile.quizzesCompleted}</strong><small><Trophy/>Saved sessions</small></div></section><div className="profile-grid"><section className="record-panel"><div className="section-heading-static"><h2><Award/> Badges</h2></div>{profile.badges.length?<div className="badge-grid">{profile.badges.map(b=><div key={`${b.name}-${b.earnedAt}`}><Award/><strong>{b.name}</strong><p>{b.description}</p><small>{new Date(b.earnedAt).toLocaleDateString()}</small></div>)}</div>:<p className="empty-record">No earned badges yet.</p>}</section><section className="record-panel"><div className="section-heading-static"><h2>Strongest categories</h2></div>{profile.strongestCategories.length?profile.strongestCategories.map((c,i)=><div className="public-strength" key={c.category}><span>{i+1}</span><strong>{c.category}</strong><b>{c.accuracy}%</b></div>):<p className="empty-record">More attempts are needed before categories can be ranked.</p>}</section></div></main>;
}
