import { AdminHeader, Notice, StatusBadge } from "@/components/admin/ui";
import { requireAdmin } from "@/lib/admin/auth";
import { adminRpc, formatAdminDate, single } from "@/lib/admin/data";
import { assignRoleAction, updateSettingAction } from "../actions";

type SettingsData={settings:Array<{key:string;value:unknown;description:string;updatedAt:string}>;admins:Array<{userId:string;username:string;displayName:string;role:string;assignedAt:string}>;roles:Array<{key:string;name:string}>;audit:Array<{id:number;admin:string;action:string;resourceType:string;resourceId:string|null;createdAt:string}>};
export default async function AdminSettings({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
  const access=await requireAdmin("settings.view");const q=await searchParams;const data=await adminRpc<SettingsData>("admin_settings_data");const canManage=access.capabilities.includes("settings.manage");const canManageAdmins=access.capabilities.includes("admins.manage");
  return <><AdminHeader title="Settings & access" description="A limited operational configuration surface and the foundation for staff access control."/><Notice error={single(q.error)} message={single(q.message)}/>
    <div className="admin-grid two"><section className="admin-panel"><div className="admin-section-heading"><h2>Operational settings</h2><span>Data-sensitive constants remain code-controlled</span></div><div className="admin-settings-list">{data.settings.map(setting=><form action={updateSettingAction} key={setting.key}><input type="hidden" name="key" value={setting.key}/><div><strong>{setting.key.replaceAll("_"," ")}</strong><small>{setting.description}</small></div><input name="value" defaultValue={typeof setting.value==="string"?setting.value:JSON.stringify(setting.value)} disabled={!canManage}/>{canManage&&<button>Save</button>}</form>)}</div></section>
      <section className="admin-panel"><div className="admin-section-heading"><h2>Assign admin role</h2><span>Super admin only</span></div>{canManageAdmins?<form className="admin-action-form" action={assignRoleAction}><label>User ID or username<input name="user" required/></label><label>Role<select name="role">{data.roles.map(role=><option value={role.key} key={role.key}>{role.name}</option>)}</select></label><label>Operation<select name="remove"><option value="false">Assign role</option><option value="true">Revoke role</option></select></label><button className="admin-button primary">Update access</button></form>:<p className="admin-empty">Only super admins can change staff access.</p>}</section></div>
    <section className="admin-panel"><div className="admin-section-heading"><h2>Authorized admins</h2><span>{data.admins.length} role assignments</span></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Admin</th><th>User ID</th><th>Role</th><th>Assigned</th></tr></thead><tbody>{data.admins.map(admin=><tr key={`${admin.userId}-${admin.role}`}><td><strong>{admin.displayName}</strong><small>@{admin.username}</small></td><td><code>{admin.userId}</code></td><td><StatusBadge value={admin.role}/></td><td>{formatAdminDate(admin.assignedAt)}</td></tr>)}</tbody></table></div></section>
  </>;
}
