"use client";
import {useEffect,useState} from "react";
import {BarChart3,BookOpen,Check,ChevronRight,CircleHelp,Flame,Home,Library,Settings,Target,Trophy,User,X,Zap} from "lucide-react";
import {createClient} from "@/utils/supabase/client";
import {isCorrectAnswer,questions as qs,type QuizQuestion as Q} from "@/lib/question-bank";
import {toProfileStats,type ProfileRow,type ProfileStats as Stats} from "@/types/database";
type View="home"|"practice"|"categories"|"progress"|"leaders"|"profile"|"results";
type A={q:Q;correct:boolean;submitted:string};
const cats=[["History","Timelines, leaders & turning points"],["Science","Biology, chemistry & physics"],["Literature","Authors, works & movements"],["Fine Arts","Painting, music & architecture"],["Geography","Places, people & landscapes"],["Civics","Government, law & institutions"],["Mythology","Gods, heroes & traditions"],["Math","Numbers, proofs & patterns"]];
const initial:Stats={xp:0,streak:0,longest:0,answered:0,correct:0,done:null};
export default function App(){const[view,setView]=useState<View>("home"),[stats,setStats]=useState(initial),[set,setSet]=useState(qs),[title,setTitle]=useState("Daily practice"),[i,setI]=useState(0),[input,setInput]=useState(""),[feedback,setFeedback]=useState<boolean|null>(null),[answers,setAnswers]=useState<A[]>([]),[loaded,setLoaded]=useState(false),[saving,setSaving]=useState(false),[saveError,setSaveError]=useState(""),[sessionXp,setSessionXp]=useState(0),[profile,setProfile]=useState({username:"player",display_name:"QuizForge Player"});
useEffect(()=>{let active=true;const load=async()=>{const supabase=createClient();const{data,error}=await supabase.from("profiles").select("username,display_name,total_xp,current_streak,longest_streak,total_answered,total_correct,last_daily_completed_on").single();if(!active)return;if(error)setSaveError("Your profile could not be loaded. Confirm the Supabase migration has been applied.");else{const row=data as ProfileRow;setStats(toProfileStats(row));setProfile({username:row.username,display_name:row.display_name})}setLoaded(true)};load();return()=>{active=false}},[]);
const accuracy=stats.answered?Math.round(stats.correct/stats.answered*100):0,today=new Intl.DateTimeFormat("en-CA").format(new Date()),done=stats.done===today;
const go=(v:View)=>{setView(v);scrollTo(0,0)},start=(cat?:string)=>{let pool=cat?qs.filter(q=>q.category===cat):qs; if(pool.length<5)pool=[...pool,...qs.filter(q=>q.category!==cat)].slice(0,5);setSet(pool);setTitle(cat?`${cat} practice`:"Daily practice");setI(0);setInput("");setFeedback(null);setAnswers([]);go("practice")};
const submit=()=>{if(!input.trim())return;const q=set[i],ok=isCorrectAnswer(q,input);setFeedback(ok);setAnswers(x=>[...x,{q,correct:ok,submitted:input}])};
const next=async()=>{if(i+1<set.length){setI(i+1);setInput("");setFeedback(null);return}setSaving(true);setSaveError("");try{const response=await fetch("/api/progress/complete",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sessionType:title==="Daily practice"?"daily":"category",category:title.replace(" practice",""),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,answers:answers.map(a=>({questionId:a.q.id,submitted:a.submitted}))})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Progress could not be saved.");setStats(data.profile as Stats);setSessionXp(data.xpEarned);go("results")}catch(error){setSaveError(error instanceof Error?error.message:"Progress could not be saved.")}finally{setSaving(false)}};
const saveProfile=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget),username=String(form.get("username")||"").trim().toLowerCase(),display_name=String(form.get("displayName")||"").trim();setSaveError("");const{error}=await createClient().from("profiles").update({username,display_name}).eq("username",profile.username);if(error)setSaveError(error.message);else setProfile({username,display_name})};
const signOut=async()=>{await createClient().auth.signOut();window.location.assign("/login")};
const nav:[[View,string,typeof Home],...Array<[View,string,typeof Home]>]=[["home","Home",Home],["categories","Categories",Library],["progress","Progress",BarChart3],["leaders","Leaders",Trophy],["profile","Profile",User]];
if(!loaded)return <div className="app-loading"><Zap fill="currentColor"/><strong>Heating the forge...</strong></div>;
return <div className="shell"><aside><div className="brand"><b><Zap fill="currentColor"/></b>QuizForge</div><nav>{nav.map(([v,l,I])=><button className={view===v?"active":""} onClick={()=>go(v)} key={v}><I/>{l}</button>)}</nav><div className="streak"><Flame/><div><strong>{stats.streak} day streak</strong><small>Keep the forge burning</small></div></div></aside><main><header><div className="mobile-brand"><Zap fill="currentColor"/>QuizForge</div><span><Flame/> {stats.streak}</span><span><Zap/> {stats.xp.toLocaleString()} XP</span><button onClick={()=>go("profile")}>{profile.display_name.split(" ").map(n=>n[0]).join("").slice(0,2).toUpperCase()}</button></header><div className="content">{saveError&&<div className="app-error">{saveError}</div>}
{view==="home"&&<HomeView stats={stats} accuracy={accuracy} done={done} start={start} go={go}/>} 
{view==="practice"&&<Practice q={set[i]} i={i} total={set.length} title={title} input={input} setInput={setInput} feedback={feedback} submit={submit} next={next} saving={saving} exit={()=>go("home")}/>} 
{view==="categories"&&<><Title over="TARGETED PRACTICE" title="Choose your arena" sub="Build depth in one subject. Each round focuses your recall around that selection."/><div className="category-grid">{cats.map(([c,d],n)=><button className="category" onClick={()=>start(c)} key={c}><b>{String(n+1).padStart(2,"0")}</b><div><h3>{c}</h3><p>{d}</p><small>{54+n*11} questions</small></div><ChevronRight/></button>)}</div></>}
{view==="progress"&&<Progress stats={stats} accuracy={accuracy}/>} {view==="leaders"&&<Leaders xp={stats.xp}/>} {view==="profile"&&<Profile stats={stats} accuracy={accuracy} profile={profile} save={saveProfile} signOut={signOut}/>} 
{view==="results"&&<Results answers={answers} daily={title==="Daily practice"} xp={sessionXp} start={start} home={()=>go("home")}/>}</div></main><nav className="bottom">{nav.map(([v,l,I])=><button className={view===v?"active":""} onClick={()=>go(v)} key={v}><I/><small>{l}</small></button>)}</nav></div>}
function HomeView({stats,accuracy,done,start,go}:{stats:Stats;accuracy:number;done:boolean;start:(c?:string)=>void;go:(v:View)=>void}){return <><div className="heading"><div><em>THURSDAY, AUGUST 13</em><h1>Ready to sharpen your recall?</h1><p>One focused round today. Every clue makes you stronger.</p></div><label>VARSITY SCHOLAR</label></div><div className="dash"><section className="daily"><em>✦ TODAY&apos;S CHALLENGE</em><h2>{done?"Daily goal complete":"Your daily 10"}</h2><p>{done?"You kept your streak alive. Target a weak category next.":"Ten mixed-category questions selected to build your range."}</p><div className="meta"><span><CircleHelp/>10 questions</span><span><Target/>Mixed topics</span><span><Zap/>Up to 145 XP</span></div><button className="primary" onClick={()=>start()}>{done?"Practice another set":"Start today's practice"}<ChevronRight/></button></section><section className="statbox"><Stat icon={<Flame/>} label="Current streak" value={`${stats.streak} days`} note="Personal best: 12"/><Stat icon={<Zap/>} label="Total XP" value={stats.xp.toLocaleString()} note="260 XP to next level"/><Stat icon={<Target/>} label="Overall accuracy" value={`${accuracy}%`} note={`Across ${stats.answered} questions`}/></section></div><div className="section-title"><div><em>KEEP IMPROVING</em><h2>Your next move</h2></div><button onClick={()=>go("categories")}>View all <ChevronRight/></button></div><div className="next"><section className="recommend"><b>Li</b><div><em>RECOMMENDED FOR YOU</em><h3>Strengthen Literature</h3><p>Your 68% accuracy is trending up. Five more clues can make it stick.</p><button onClick={()=>start("Literature")}>Practice Literature <ChevronRight/></button></div></section><section className="rank"><Trophy/><div><em>WEEKLY RANK</em><h2>#12</h2><p>You&apos;re 90 XP from the top 10</p><i><b/></i></div></section></div><div className="section-title"><div><em>RECENT FORM</em><h2>Category pulse</h2></div><button onClick={()=>go("progress")}>Full progress <ChevronRight/></button></div><div className="pulse">{[["History",82],["Science",76],["Literature",68],["Fine Arts",61]].map(([c,n])=><section key={c as string}><span>{c}<b>{n}%</b></span><i><b style={{width:`${n}%`}}/></i><small>Last 30 questions</small></section>)}</div></>}
function Practice({q,i,total,title,input,setInput,feedback,submit,next,saving,exit}:{q:Q;i:number;total:number;title:string;input:string;setInput:(s:string)=>void;feedback:boolean|null;submit:()=>void;next:()=>void;saving:boolean;exit:()=>void}){return <div className="practice"><div className="practice-top"><button onClick={exit} aria-label="Exit practice"><X/></button><div><span>{title}</span><i>{Array.from({length:total}).map((_,n)=><b className={n<i?"done":n===i?"now":""} key={n}/>)}</i></div><strong>{i+1} / {total}</strong></div><article><div className="qmeta"><b>{q.category}</b><span>{q.topic}</span></div><h1>{q.prompt}</h1>{feedback===null?<form onSubmit={e=>{e.preventDefault();submit()}}><label>Your answer<input autoFocus value={input} onChange={e=>setInput(e.target.value)} placeholder="Type your answer..."/></label><button className="primary" disabled={!input.trim()}>Submit answer <ChevronRight/></button></form>:<div className={`feedback ${feedback?"correct":"wrong"}`}><div><b>{feedback?<Check/>:<X/>}</b><span><em>{feedback?"CORRECT +10 XP":"NOT QUITE"}</em><h2>{feedback?"Nice recall.":`Answer: ${q.answer}`}</h2></span></div><section><strong>WHY IT MATTERS</strong><p>{q.explanation}</p></section><button className="primary" disabled={saving} onClick={next}>{saving?"Saving progress...":i+1===total?"See results":"Next question"}<ChevronRight/></button></div>}</article><button className="report"><CircleHelp/> Report this question</button></div>}
function Progress({stats,accuracy}:{stats:Stats;accuracy:number}){return <><Title over="YOUR GROWTH" title="Progress that tells a story" sub="See what is sticking and where your next breakthrough lives."/><div className="kpis"><Stat icon={<BookOpen/>} label="Questions answered" value={String(stats.answered)} note="Lifetime"/><Stat icon={<Target/>} label="Overall accuracy" value={`${accuracy}%`} note="All categories"/><Stat icon={<Flame/>} label="Longest streak" value={`${stats.longest} days`} note="Personal best"/><Stat icon={<Zap/>} label="Lifetime XP" value={stats.xp.toLocaleString()} note="Varsity Scholar"/></div><section className="mastery"><em>MASTERY MAP</em><h2>Accuracy by category</h2>{[["History",82,38],["Science",76,33],["Literature",68,29],["Fine Arts",61,21],["Geography",74,25]].map(([c,n,a])=><div key={c as string}><strong>{c}</strong><i><b style={{width:`${n}%`}}/></i><b>{n}%</b><small>{a} answered</small></div>)}</section></>}
function Leaders({xp}:{xp:number}){const p=[["Ava M.",1760],["Jordan L.",1580],["Sam K.",1490],["Nina P.",1375],["You",xp],["Eli T.",1180]].sort((a,b)=>(b[1] as number)-(a[1] as number));return <><Title over="FRIENDLY COMPETITION" title="Weekly leaderboard" sub="Rankings reset every Monday. Learn consistently and the points follow."/><div className="tabs"><button>This week</button><button>All time</button></div><div className="leaders">{p.map(([name,n],i)=><div className={name==="You"?"you":""} key={name as string}><b>#{i+1}</b><span>{(name as string).split(" ").map(x=>x[0]).join("")}</span><p><strong>{name}</strong><small>{i<3?"Varsity Scholar":"Rising Scholar"}</small></p><strong>{(n as number).toLocaleString()} <small>XP</small></strong></div>)}</div></>}
function Profile({stats,accuracy,profile,save,signOut}:{stats:Stats;accuracy:number;profile:{username:string;display_name:string};save:(event:React.FormEvent<HTMLFormElement>)=>void;signOut:()=>void}){const initials=profile.display_name.split(" ").map(n=>n[0]).join("").slice(0,2).toUpperCase();return <><Title over="YOUR ACCOUNT" title="Scholar profile" sub="Your QuizForge identity and lifetime record."/><div className="profile"><section><b>{initials}</b><h2>{profile.display_name}</h2><p>@{profile.username}</p><label>VARSITY SCHOLAR</label><div><span><strong>{stats.xp.toLocaleString()}</strong>XP</span><span><strong>{stats.answered}</strong>ANSWERS</span><span><strong>{accuracy}%</strong>ACCURACY</span></div></section><section><h2><Settings/> Account settings</h2><p>Update how you appear on QuizForge.</p><form onSubmit={save}><label>Display name<input name="displayName" required maxLength={40} defaultValue={profile.display_name}/></label><label>Username<input name="username" required minLength={3} maxLength={24} pattern="[a-z0-9_]+" defaultValue={profile.username}/></label><button className="primary" type="submit">Save changes</button><button className="profile-signout" type="button" onClick={signOut}>Sign out</button></form></section></div></>}
function Results({answers,daily,xp,start,home}:{answers:A[];daily:boolean;xp:number;start:(c?:string)=>void;home:()=>void}){const n=answers.filter(a=>a.correct).length;return <div className="results"><Trophy/><em>SESSION COMPLETE</em><h1>That round is in the books.</h1><p>You showed up, tested your recall, and left sharper.</p><div><span><strong>{n}/{answers.length}</strong>Correct</span><span><strong>+{xp}</strong>XP earned</span><span><strong>{Math.round(n/answers.length*100)}%</strong>Accuracy</span></div><section><Flame/><p><strong>{daily?"Your daily streak is safe":"Targeted work pays off"}</strong><small>{daily?"Come back tomorrow to keep it moving.":"Your progress has been updated."}</small></p></section><button className="primary" onClick={()=>start("Literature")}>Practice a weak area <ChevronRight/></button><button className="secondary" onClick={home}>Back to dashboard</button></div>}
function Title({over,title,sub}:{over:string;title:string;sub:string}){return <div className="title"><em>{over}</em><h1>{title}</h1><p>{sub}</p></div>};function Stat({icon,label,value,note}:{icon:React.ReactNode;label:string;value:string;note:string}){return <div className="stat"><b>{icon}</b><div><span>{label}</span><strong>{value}</strong><small>{note}</small></div></div>}
