import Link from "next/link";
import { AdminHeader, Pagination, StatusBadge } from "@/components/admin/ui";
import { requireAdmin } from "@/lib/admin/auth";
import { adminRpc, formatAdminDate, integer, single } from "@/lib/admin/data";

type Row={rank:number;id:string;username:string;displayName:string;xp:number;questions:number;accuracy:number;sessions:number;streak:number;lastActiveAt:string|null;status:string;eligible:boolean}; type Result={data:Row[];pagination:{page:number;pageSize:number;total:number;totalPages:number}};
export default async function AdminLeaderboards({ searchParams }: { searchParams: Promise<Record<string,string|string[]|undefined>> }) {
  await requireAdmin("leaderboards.view"); const q=await searchParams; const period=single(q.period,"weekly"); const category=single(q.category); const search=single(q.search); const from=single(q.from); const to=single(q.to); const page=Math.max(1,integer(q.page,1)); const pageSize=50;
  const result=await adminRpc<Result>("admin_leaderboard",{p_period:period,p_category:category,p_from:from||null,p_to:to||null,p_search:search,p_page:page,p_page_size:pageSize});
  return <><AdminHeader title="Full leaderboard" description="Reproduce rankings across time windows and investigate the activity behind each score." />
    <form className="admin-toolbar"><label>Period<select name="period" defaultValue={period}><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="all_time">All time</option><option value="custom">Custom</option></select></label><label>Category<input name="category" defaultValue={category} placeholder="All categories" /></label><label className="admin-search">User search<input name="search" defaultValue={search} /></label><label>From<input type="date" name="from" defaultValue={from} /></label><label>To<input type="date" name="to" defaultValue={to} /></label><button className="admin-button primary">Apply</button></form>
    <div className="admin-table-meta"><strong>{result.pagination.total} ranked users</strong><span>{period.replace("_"," ")} · {category||"All categories"}</span></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Rank</th><th>User</th><th>XP</th><th>Questions</th><th>Accuracy</th><th>Sessions</th><th>Streak</th><th>Last active</th><th>Eligibility</th></tr></thead><tbody>{result.data.map(row=><tr key={row.id}><td><strong>#{row.rank}</strong></td><td><Link className="admin-link" href={`/admin/users/${row.id}`}>{row.displayName}</Link><small>@{row.username}</small></td><td>{row.xp.toLocaleString()}</td><td>{row.questions}</td><td>{row.accuracy}%</td><td>{row.sessions}</td><td>{row.streak}</td><td>{formatAdminDate(row.lastActiveAt)}</td><td>{row.eligible?<StatusBadge value={row.status}/>:<StatusBadge value="excluded"/>}</td></tr>)}</tbody></table>{!result.data.length&&<p className="admin-empty">No leaderboard activity matches these filters.</p>}</div>
    <Pagination base="/admin/leaderboards" page={page} totalPages={result.pagination.totalPages} params={{period,category,search,from,to}} /></>;
}
