import Link from "next/link";
import { AdminHeader, Metric, Notice, StatusBadge } from "@/components/admin/ui";
import { requireAdmin } from "@/lib/admin/auth";
import { adminRpc, formatAdminDate, single } from "@/lib/admin/data";
import { updateUserAction } from "../../actions";

type Detail = { profile: { id:string;username:string;displayName:string;email:string|null;joinedAt:string;lastActiveAt:string|null;status:string;leaderboardEligible:boolean;xp:number;streak:number;longestStreak:number;answered:number;correct:number;accuracy:number;sessions:number }; attempts:Array<{id:string;completedAt:string;type:string;category:string|null;questions:number;correct:number;accuracy:number;xp:number}>; categories:Array<{category:string;attempts:number;correct:number;accuracy:number;sufficient_sample:boolean}>; activity:Array<{at:string;type:string;description:string}> };
type PrivateProfile = { email:string|null;phone:string|null;age:number|null;gender:string|null;complete:boolean };

export default async function AdminUserDetail({ params, searchParams }: { params: Promise<{ userId: string }>; searchParams: Promise<Record<string,string|string[]|undefined>> }) {
  const access = await requireAdmin("users.view"); const { userId } = await params; const query = await searchParams;
  const [data, privateProfile] = await Promise.all([adminRpc<Detail | null>("admin_user_detail", { p_user_id: userId }), adminRpc<PrivateProfile | null>("admin_user_profile", { p_user_id: userId })]);
  if (!data) return <><AdminHeader title="User not found" description="This account does not exist." /><Link className="admin-link" href="/admin/users">Back to users</Link></>;
  const p = data.profile; const canManage = access.capabilities.includes("users.manage");
  return <><AdminHeader title={p.displayName} description={`@${p.username} · ${p.id}`} action={<Link className="admin-button" href="/admin/users">Back to users</Link>} /><Notice error={single(query.error)} message={single(query.message)} />
    <section className="admin-profile-strip"><div><span>Account</span><StatusBadge value={p.status} /><small>{p.email || "Email restricted"}</small><small>Joined {formatAdminDate(p.joinedAt)}</small><small>Last active {formatAdminDate(p.lastActiveAt)}</small></div><Metric label="Lifetime XP" value={p.xp.toLocaleString()} /><Metric label="Accuracy" value={`${p.accuracy}%`} /><Metric label="Sessions" value={p.sessions} /><Metric label="Current streak" value={p.streak} /><Metric label="Longest streak" value={p.longestStreak} /></section>
    <section className="admin-panel"><div className="admin-section-heading"><h2>Profile details</h2><span>{privateProfile?.complete ? "Complete profile" : "Incomplete profile"}</span></div><dl className="admin-profile-details"><div><dt>Name</dt><dd>{p.displayName}</dd></div><div><dt>Username</dt><dd>@{p.username}</dd></div><div><dt>Email</dt><dd>{privateProfile?.email || "Not provided"}</dd></div><div><dt>Phone</dt><dd>{privateProfile?.phone || "Not provided"}</dd></div><div><dt>Age</dt><dd>{privateProfile?.age ?? "Not provided"}</dd></div><div><dt>Gender</dt><dd>{privateProfile?.gender ? privateProfile.gender.replaceAll("_", " ") : "Not provided"}</dd></div></dl></section>
    <div className="admin-grid two"><section className="admin-panel"><div className="admin-section-heading"><h2>Category performance</h2><span>Weak area requires 10+ attempts</span></div><div className="admin-ranked-list">{data.categories.map((row) => <div key={row.category}><strong>{row.category}</strong><span>{row.attempts} attempts</span><b>{row.accuracy}% {row.sufficient_sample && row.accuracy < 50 ? "· Weak area" : ""}</b></div>)}{!data.categories.length && <p className="admin-empty">No category data yet.</p>}</div></section>
      <section className="admin-panel"><div className="admin-section-heading"><h2>Admin controls</h2><span>{p.leaderboardEligible ? "Leaderboard eligible" : "Excluded from rankings"}</span></div>{canManage ? <form className="admin-action-form" action={updateUserAction}><input type="hidden" name="userId" value={p.id} /><label>Account status<select name="status" defaultValue={p.status}><option value="active">Active</option><option value="suspended">Suspended</option></select></label><label>Leaderboard<select name="eligible" defaultValue={String(p.leaderboardEligible)}><option value="true">Eligible</option><option value="false">Excluded</option></select></label><label>Required reason<textarea name="reason" required minLength={3} placeholder="Why is this change needed?" /></label><button className="admin-button danger">Save controlled change</button></form> : <p className="admin-empty">Your role has read-only user access.</p>}</section></div>
    <section className="admin-panel"><div className="admin-section-heading"><h2>Recent quiz attempts</h2><span>Latest 25 sessions</span></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Completed</th><th>Type</th><th>Category</th><th>Score</th><th>Accuracy</th><th>XP</th></tr></thead><tbody>{data.attempts.map((attempt) => <tr key={attempt.id}><td>{formatAdminDate(attempt.completedAt)}</td><td>{attempt.type}</td><td>{attempt.category || "Mixed"}</td><td>{attempt.correct}/{attempt.questions}</td><td>{attempt.accuracy}%</td><td>{attempt.xp}</td></tr>)}</tbody></table>{!data.attempts.length && <p className="admin-empty">No completed attempts.</p>}</div></section>
    <section className="admin-panel"><div className="admin-section-heading"><h2>Activity history</h2><span>Meaningful events</span></div><ol className="admin-timeline">{data.activity.map((event, index) => <li key={`${event.at}-${index}`}><time>{formatAdminDate(event.at)}</time><strong>{event.description}</strong><small>{event.type}</small></li>)}</ol></section>
  </>;
}
